# Generated by Django 3.2.11 on 2022-05-09 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dialogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_utt_1', models.TextField(verbose_name='Пользовательское сообщение 1')),
                ('bot_utt_1', models.TextField(verbose_name='Ответ бота 1')),
                ('user_utt_2', models.TextField(verbose_name='Пользовательское сообщение 2')),
                ('bot_utt_2', models.TextField(verbose_name='Ответ бота для разметки')),
            ],
            options={
                'verbose_name': 'Реплика для разметки',
                'verbose_name_plural': 'Реплики для разметки',
            },
        ),
        migrations.CreateModel(
            name='LabelledSSI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.PositiveSmallIntegerField(choices=[(0, 'Groundedness'), (1, 'Helpfulness'), (2, 'Interestingness'), (3, 'Safety'), (4, 'Sensibleness'), (5, 'Specificity')], default=0, null=True, verbose_name='Метка')),
                ('start_labeling', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Дата начала разметки')),
                ('end_labeling', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Дата окончания разметки')),
                ('changed_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('dialog', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labels_for_dialog', to='home.dialogs')),
            ],
            options={
                'verbose_name': 'Метки реплики бота',
                'verbose_name_plural': 'Метки реплик бота',
            },
        ),
    ]
