# Generated by Django 3.2.11 on 2022-05-10 15:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_labelledssi_changed_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labelledssi',
            name='end_labeling',
        ),
        migrations.RemoveField(
            model_name='labelledssi',
            name='start_labeling',
        ),
        migrations.AddField(
            model_name='dialogs',
            name='is_labelled',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Не размечен'), (1, 'Размечен')], default=0, null=True, verbose_name='Отметка о разметке'),
        ),
        migrations.AddField(
            model_name='labelledssi',
            name='labeling_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Дата разметки'),
        ),
    ]
